baseURL = 'https://photographie.victorprouff.fr/'
languageCode = "fr-fr"
title = 'Victor Prouff - Photographie'
theme = 'gallery'
copyright = "© Victor Prouff"
defaultContentLanguage = "fr"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeZone = "Europe/Paris"
timeout = "1200s"

[params]
  defaultTheme = "dark"
  description = "Site photo de Victor Prouff. Venez découvrir mon univers"
  [params.author]
    email = "contact@victorprouff.fr"
    name = "Victor Prouff"
  [params.socialIcons]
    instagram = "https://www.instagram.com/victor.prouff.photographie/"
    github = "https://github.com/victorprouff/"
    email = "mailto:contact@victorprouff.fr"
    website = "https://blog.victorprouff.fr"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

# ----------------------OUTPUT------------------------ #
[outputs]
  home = ["HTML", "RSS", "htaccess", "humanstxt"]
  page = ["HTML"]
  section = ["HTML"]

[outputFormats]
[outputFormats.htaccess]
    baseName = ""
    isPlainText = true
    mediaType = "text/htaccess"

[outputFormats.humanstxt]
    baseName = "humans"
    isPlainText = true
    mediaType = "text/plain"

# Permet de spécifier un type custom ici, htaccess  
[mediaTypes]
  [mediaTypes."text/htaccess"]
    suffixes = ["htaccess"]

# --------------------END-OUTPUT--------------------- #

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

# [module]
#   [module.hugoVersion]
#     min = "0.121.2"
#   [[module.imports]]
#     path = "github.com/nicokaiser/hugo-theme-gallery"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/victorprouff/photography-hugo"
    weight = 5

[services]
  [services.rss]
    limit = 100
